"""empty message

Revision ID: a05c2de2361a
Revises: 2018a69bdd14
Create Date: 2024-03-12 21:13:28.415701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05c2de2361a'
down_revision = '2018a69bdd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['thread_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.alter_column('private_messages', 'content',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=5000),
               existing_nullable=False)
    op.alter_column('thread_comments', 'content',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('threads', 'content',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threads', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('thread_comments', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('private_messages', 'content',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_table('comment_likes')
    # ### end Alembic commands ###
